version: '3.8'

services:
  dispatcher:
    build: .
    read_only: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - REDIS_HOST=${REDIS_HOST:-host.docker.internal}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_CHANNEL=${REDIS_CHANNEL:-github-webhook-push}
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json:ro
