name: Update Go Version
on:
  schedule:
    - cron: '0 0 * * 3' # Runs every Wednesday
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable' # Always gets the latest stable version

      - name: Update go.mod
        run: |
          LATEST_GO=$(go version | cut -d ' ' -f 3 | sed 's/go//' | cut -d '.' -f 1,2)
          go mod edit -go=$LATEST_GO
          go mod tidy
          echo "LATEST_GO=$LATEST_GO" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "build(deps): bump go version to ${{ env.LATEST_GO }}"
          title: "Bump Go version to ${{ env.LATEST_GO }}"
          branch: "update-go-version"
          base: main
          delete-branch: true
